modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved"
[[mods]]
modId="yippee"
version="1.19.2-1.3.0"
displayName="Yippee"
logoFile= "icon.png"
credits="Orcinus, Dopadream"
authors="Ninni"
description='''
A not too serious minecraft mod that plans on adding many meme related features in a believable way.!
'''
[[dependencies.yippee]]
modId="forge"
mandatory=true
versionRange="[39,)"
ordering="NONE"
side="BOTH"
[[dependencies.yippee]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
