modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved"
[[mods]]
modId="yippee"
version="1.19-2.0.0"
displayName="Yippee"
logoFile= "icon.png"
credits=""
authors="Ninni"
description='''
YIPPEEEEEEEEEEEEEEEEEEEEEEE!
'''
[[dependencies.yippee]]
modId="forge"
mandatory=true
versionRange="[39,)"
ordering="NONE"
side="BOTH"
[[dependencies.yippee]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
